from dvi_spec import (get_set_char_instruction,
                      get_set_rule_instruction,
                      get_put_char_instruction,
                      get_put_rule_instruction,
                      get_no_op_instruction,
                      get_begin_page_instruction,
                      get_end_page_instruction,
                      get_push_instruction,
                      get_pop_instruction,

                      get_right_instruction,
                      get_right_w_instruction,
                      get_set_w_then_right_w_instruction,
                      get_right_x_instruction,
                      get_set_x_then_right_x_instruction,

                      get_down_instruction,
                      get_down_y_instruction,
                      get_set_y_then_down_y_instruction,
                      get_down_z_instruction,
                      get_set_z_then_down_z_instruction,

                      get_select_font_nr_instruction,
                      get_do_special_instruction,
                      get_define_font_nr_instruction,

                      get_preamble_instruction,
                      get_postamble_instruction,
                      get_post_postamble_instruction,
                      )
